packages:
  - apps/*
  - packages/*
  - templates/*

blockExoticSubdeps: true

catalog:
  '@aws-sdk/client-dynamodb': 3.651.1
  '@aws-sdk/lib-dynamodb': 3.651.1
  '@aws-sdk/util-dynamodb': 3.651.1
  '@graphql-codegen/cli': 5.0.2
  '@graphql-codegen/introspection': 4.0.3
  '@graphql-codegen/typed-document-node': 5.0.5
  '@graphql-codegen/typescript': 4.0.5
  '@graphql-codegen/typescript-operations': 4.1.3
  '@graphql-codegen/typescript-urql': 4.0.0
  '@graphql-typed-document-node/core': 3.2.0
  '@hookform/resolvers': 3.3.1
  '@opentelemetry/api': 1.9.0
  '@opentelemetry/api-logs': 0.57.2
  '@opentelemetry/exporter-metrics-otlp-http': 0.57.2
  '@opentelemetry/exporter-trace-otlp-http': 0.57.2
  '@opentelemetry/instrumentation': 0.57.2
  '@opentelemetry/instrumentation-aws-sdk': 0.49.1
  '@opentelemetry/instrumentation-http': 0.57.2
  '@opentelemetry/resources': 1.30.1
  '@opentelemetry/sdk-logs': 0.57.2
  '@opentelemetry/sdk-metrics': 1.30.1
  '@opentelemetry/sdk-trace-node': 1.30.1
  '@opentelemetry/semantic-conventions': 1.30.0
  '@saleor/app-sdk': 1.6.0
  '@saleor/macaw-ui': 1.3.1
  '@sentry/cli': 1.77.3
  '@sentry/nextjs': 9.8.0
  '@t3-oss/env-nextjs': 0.11.1
  '@tanstack/react-query': 4.29.19
  '@trpc/client': 10.45.3
  '@trpc/next': 10.45.3
  '@trpc/react-query': 10.45.3
  '@trpc/server': 10.45.3
  '@types/node': 22.13.10
  '@vercel/otel': 1.10.1
  '@vitejs/plugin-react': 4.7.0
  '@vitest/coverage-v8': 3.1.1
  decimal.js-light: 2.5.1
  dotenv: 16.3.1
  dynamodb-toolbox: 2.6.4
  eslint: 9.23.0
  eslint-plugin-n: 17.16.2
  graphql: 16.7.1
  graphql-tag: 2.12.6
  jsdom: 20.0.3
  json-schema-to-typescript: 15.0.4
  modern-errors: 7.0.1
  modern-errors-serialize: 6.1.0
  neverthrow: 6.2.1
  next: 15.2.8
  next-test-api-route-handler: 4.0.16
  node-mocks-http: 1.16.1
  react: 18.2.0
  react-dom: 18.2.0
  react-hook-form: 7.43.9
  react-is: 18.2.0
  tsx: 4.19.3
  typescript: 5.8.2
  urql: 4.0.4
  usehooks-ts: 2.9.1
  vite: 6.2.4
  vite-tsconfig-paths: 5.1.4
  vitest: 3.1.1
  zod: 3.21.4
  zod-validation-error: 3.4.0

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - esbuild
  - highlight.js
  - msw
  - protobufjs
  - sharp

overrides:
  form-data@3.0.1: 3.0.4

trustPolicy: no-downgrade
